### ISSUE TITLE
Required password length is not taken from settings

### ISSUE THREAD

**Issue by Benjamin-K** [jvm-tech/JvMTECH.NeosHardening#1]
Hey, nice package. I've already searched for a package to set the password strength for a while (see also neos/flow-development-collection#2662). 

One little thing i found when checking the code:
The required password length is currently hardcoded (See [/Classes/Service/UserServiceAspect.php#L57](https://github.com/jvm-tech/JvMTECH.NeosHardening/blob/main/Classes/Service/UserServiceAspect.php#L57)). This should be changed to reflect the option defined in Settings.yaml.

**Comment by sbruggmann** [comment]
Thanks for reporting :pray:
